/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllBox: typeof import('./src/components/AllFunc/AllBox.vue')['default']
    AllFunc: typeof import('./src/components/AllFunc/index.vue')['default']
    AllSet: typeof import('./src/components/AllFunc/AllSet.vue')['default']
    Background: typeof import('./src/components/Background/index.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Menu: typeof import('./src/components/Layout/Menu.vue')['default']
    Nav: typeof import('./src/components/AllFunc/Nav.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    SearchEngine: typeof import('./src/components/SearchInput/SearchEngine.vue')['default']
    SearchInp: typeof import('./src/components/SearchInput/SearchInp.vue')['default']
    ShortCut: typeof import('./src/components/AllFunc/Box/ShortCut.vue')['default']
    Suggestions: typeof import('./src/components/SearchInput/Suggestions.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WeatherTime: typeof import('./src/components/WeatherTime.vue')['default']
  }
}
