/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddShortcut: typeof import('./components/AllFunc/Box/AddShortcut.vue')['default']
    AllFunc: typeof import('./components/AllFunc/index.vue')['default']
    AllSet: typeof import('./components/AllFunc/AllSet.vue')['default']
    Background: typeof import('./components/Background/index.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu/index.vue')['default']
    Cover: typeof import('./components/Cover.vue')['default']
    DefaultShortCut: typeof import('./components/AllFunc/Box/DefaultShortCut.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./components/Footer.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    MainColorModal: typeof import('./components/MainColorModal/index.vue')['default']
    Menu: typeof import('./components/Layout/Menu.vue')['default']
    Provider: typeof import('./components/Provider.vue')['default']
    SearchEngine: typeof import('./components/SearchInput/SearchEngine.vue')['default']
    SearchInp: typeof import('./components/SearchInput/SearchInp.vue')['default']
    ShorcutEditCategoryName: typeof import('./components/AllFunc/Box/ShorcutEditCategoryName.vue')['default']
    ShortCut: typeof import('./components/AllFunc/Box/ShortCut.vue')['default']
    ShortCutLayout: typeof import('./components/AllFunc/Box/ShortCutLayout.vue')['default']
    Suggestions: typeof import('./components/SearchInput/Suggestions.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    ToolBox: typeof import('./components/AllFunc/ToolBox.vue')['default']
  }
}
