name: wonderfulJourney

on: push

jobs:
  build:
    name: wonderfulJourney
    runs-on: windows-latest
    steps:
      - name: 读取仓库内容
        use: actions/checkout@v4

      - name: 安装依赖
        run: npm install
        
        - name: 打包
        run: npm run build
